version: '3.8'

services:
  app:
    build: .
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=development

    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev